kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-public-ingress-from-tenant
  namespace: tenant1-ns1
spec:
  podSelector: {}
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kourier-system
      ports:
        - protocol: TCP
          port: 8080
  policyTypes:
    - Egress
