apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pong
  namespace: tenant1-ns1
  labels:
    app.kubernetes.io/name: pong
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: docker.io/villardl/pong
          ports:
            - containerPort: 8080
